### ISSUE TITLE
Hello, the server for the test submission probably has broke down, can you check if the sever broke down?

### ISSUE THREAD

**Issue by JThuge** [miccunifi/SEARLE#9]

**Comment by ABaldrati** [comment]
Hi @JThuge 

Thank you for your interest in our work and for using the CIRCO dataset.

Yes, you're right, the evaluation server is currently down due to connection problems with our lab's servers. If you urgently need to validate your predictions (e.g. for the AAAI deadline) or need more information, please visit https://github.com/miccunifi/CIRCO/issues/3.

**Comment by JThuge** [comment]
Thank you for promptly responding to and handling my request!

**Comment by ABaldrati** [comment]
Hi @JThuge

I am happy to announce that the evaluation server is working again!
We are no longer accepting submissions by mail.
